In [1]:
import pathlib
import h5py
import numpy as np
from plotly import graph_objects as go
import plotly.io as pio

In [2]:
pio.templates.default = "plotly_dark"

In [3]:
%load_ext autoreload
%autoreload 2

from training.data.partnet import HdfIO

In [27]:
file = h5py.File(r"D:\Datasets\compressed_partnet\train.h5", "r") 

In [28]:
file.keys()

<KeysViewHDF5 ['data', 'data_num', 'label_seg']>

In [30]:
samples = file["data"][:10]

In [31]:
seg_map = file["label_seg"][:10]

In [32]:
file.close()

In [34]:
seg_map[8]

array([0, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [9]:
samples.shape

(10, 4096, 3)

In [16]:
seg_map[index]

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [20]:
seg_map[3]

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [35]:
index = 8

figure = go.Figure(
    data=[
        go.Scatter3d(
        x=samples[index, :, 0],
        y=samples[index, :, 1],
        z=samples[index, :, 2],
        marker=dict(
            color=seg_map[index],
            size=2
        ),
        mode="markers")
    ],
    layout=dict(scene=dict(aspectmode="data"))
)

In [36]:
figure.show()